services:
  app:
    build: .
    ports:
      - "8123:8123"
    environment:
      - MODEL_PATH=/usr/src/app/model
    volumes:
      - .:/usr/src/app
      - /usr/src/app/model
      - /usr/src/app/.pytest_cache
    command: uvicorn main:app --host 0.0.0.0 --port 8123 --reload
