services:
  nsfw-check-api:
    build: .
    ports:
      - "8123:8123"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pytest_cache
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8123 --reload
