services:
  nsfw-check-api:
    image: ghcr.io/unisa-groups/nsfw-check-api:sha-3d1eb4e
    restart: unless-stopped
    ports:
      - "30000:8123"
    volumes:
      - /home/git/docker/nsfw-check-api/:/usr/src/app/model
