[project]
name = "nsfw-check-api"
version = "0.1.0"
description = "Detects NSFW images"
requires-python = ">=3.12,<3.13"
dependencies = [
    'torch>=2.9.1; sys_platform == "linux"',
    "transformers>=5.3.0",
    "fastapi>=0.135.1",
    "httpx>=0.28.1",
    "numpy>=2.4.3",
    "pillow>=12.1.1",
    "python-multipart>=0.0.22",
    "uvicorn>=0.41.0",
    "pytest>=9.0.2",
    "huggingface-hub==1.6.0",
]